### ISSUE TITLE
no module named xmltodict

### ISSUE THREAD

**Issue by tino767** [Gamegenorator/WogglAI-FuctionalScript#1]
hey pal, i followed all your steps to fix woggle and when i came to the part where i run it it said ImportError:no module named xmltodict. as far as i know i followed all the steps the best i could. do you know how to fix this?

**Comment by tino767** [comment]
> hey pal, i followed all your steps to fix woggle and when i came to the part where i run it it said ImportError:no module named xmltodict. as far as i know i followed all the steps the best i could. do you know how to fix this?

fixed xmltodict but now it says no jaraco

**Comment by tino767** [comment]
> > hey pal, i followed all your steps to fix woggle and when i came to the part where i run it it said ImportError:no module named xmltodict. as far as i know i followed all the steps the best i could. do you know how to fix this?
> 
> fixed xmltodict but now it says no jaraco

never mind nothing is working XD. im back at xmltodict

**Comment by tino767** [comment]
> hey pal, i followed all your steps to fix woggle and when i came to the part where i run it it said ImportError:no module named xmltodict. as far as i know i followed all the steps the best i could. do you know how to fix this?

so ive tried many things and installed it in a command line with pip however when i try to import it in python it says theres no module names (module name)

**Comment by Gamegenorator** [comment]
@tino767 Hmm... Did you create a WolframAlpha account? And did you only try running it in the command line?

**Comment by Gamegenorator** [comment]
No responses received, if anyone else has this problem feel free to re-open this issue but unless there is anything else I'm going to close this for now.
