### ISSUE TITLE
Keeps saying "no module named 'wolframalpha'"

### ISSUE THREAD

**Issue by Aiki-bot51** [Gamegenorator/WogglAI-FuctionalScript#2]
what is happening? i downloaded the wolframalpha, used the appid, but keeps saying that! help pls
![wolframalpha problem](https://user-images.githubusercontent.com/48476126/55006923-19430700-5011-11e9-967e-7e763ab76411.PNG)

**Comment by Aiki-bot51** [comment]
just came, I figured it out! after downloading phyton, search cmd on the search next to windows button on screen. type "pip install wolframalpha api"

**Comment by Gamegenorator** [comment]
@Aiki-bot51 Is there a reason you re-opened this issue?

**Comment by Gamegenorator** [comment]
@Aiki-bot51 Is there a reason you re-opened this issue? I need to know before I can officially merge the branch and update the README. Also, what version of Windows are you using?

**Comment by thebeancounter** [comment]
I am still getting this error, after using pip install wolframalpha and wolframalpha api, is this still a known issue with conda and python 3.6?

**Comment by Gamegenorator** [comment]
@thebeancounter There is no need to download WolframAlpha, Just go to there website, create an account and get an appid.

**Comment by Gamegenorator** [comment]
No responses received, if anyone else has this problem feel free to re-open this issue but unless there is anything else I'm going to close this for now.

**Comment by nikhilu369** [comment]
even keep getting the error ModuleNotFoundError: No module named 'wolframalpha'
but it runs perfectly on jupyter notebook it shows this error when i run it as .py file or default python IDLE

**Comment by MicroCrusher** [comment]
I am having this issue. Working on creating batch file to run virtual assistant from desktop.

**Comment by Gamegenorator** [comment]
@MicroCrusher Are you trying to run the script on Windows? Can you provide any more details about what you're doing?
